name: pytest --last-failed

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']
   
    steps:
    # Setup
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        echo ${{ toJson(matrix) }}
        pip install pytest

    - name: pytest (--last-failed)
      uses: sjvrijn/pytest-last-failed@v1