name: pytest --last-failed

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
   
    steps:
    # Setup
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        pip install pytest


    # Initial restore of cache, if it exists
    - uses: actions/cache/restore@v3
      id: cache
      with:
        path: .pytest_cache
        key: pytest-cache-${{github.event.number}}

    - name: Check cache length
      run: |
        echo "CACHE_LENGTH=$( pytest --collect-only -qqq --no-header --no-summary --cache-show cache/lastfailed | sed -n '4 p' | wc -c )" >> "$GITHUB_ENV"


    # Full run of pytest on a missing or empty pytest cache
    - name: Run all tests
      id: run_all
      if: |
        steps.cache.outputs.cache-hit != 'true' ||
        env.CACHE_LENGTH <= 5 
      run: |
        pytest tests.py

    - name: Cache .pytest_cache for future --last-failed
      uses: actions/cache/save@v3
      if: always() && steps.run_all.outcome == 'failure'
      with:
        path: .pytest_cache
        key: pytest-cache-${{github.event.number}}

    - name: Check cache length (again)
      if: always() && steps.run_all.outcome == 'failure'
      run: |
        echo "CACHE_LENGTH=$( pytest --collect-only -qqq --no-header --no-summary --cache-show cache/lastfailed | sed -n '4 p' | wc -c )" >> "$GITHUB_ENV"


    # If some tests previously failed, i.e., a non-empty cache exists, run pytest --last-failed
    - name: Run pytest --last-failed
      id: last_failed
      if: |
        always() &&
        steps.run_all.outcome != 'skipped' &&
        steps.cache.outputs.cache-hit == 'true' &&
        env.CACHE_LENGTH > 5
      run: |
        pytest --last-failed tests.py

    - uses: actions/cache/save@v3
      if: always() && steps.last_failed.outcome != 'skipped'
      with:
        path: .pytest_cache
        key: pytest-cache-${{github.event.number}}



    # If all tests from pytest --last-failed succeeded, run all tests with a clean cache
    - name: With last failed fixed, run all tests
      id: alltests
      if: always() && steps.last_failed.outcome == 'success'
      run: |
        pytest --cache-clear tests.py

    # Update cache again for future runs
    - name: Update pytest cache
      uses: actions/cache/save@v3
      if: always() && steps.last_failed.outcome == 'success'
      with:
        path: .pytest_cache
        key: pytest-cache-${{github.event.number}}  
