name: pytest --last-failed

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']
   
    steps:
    # Setup
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        MY_STRING=$(cat << EOF
        ${{ toJson(matrix) }}
        EOF
        )
        MY_STRING="${MY_STRING//'%'/'%25'}"
        MY_STRING="${MY_STRING//$'\n'/'%0A'}"
        MY_STRING="${MY_STRING//$'\r'/'%0D'}"
        echo "MATRIX_HASH=$($MY_STRING | md5sum | cut -d' ' -f1)" >> $GITHUB_ENV
        echo ${{ env.MATRIX_HASH }}
        pip install pytest

    - name: pytest (--last-failed)
      uses: sjvrijn/pytest-last-failed@v1